version: '2'
services:
  db:
    build: ./db
    container_name: db
    expose:
      - "5432"
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_PASSWORD=password
  server:
    image: spring-test
    container_name: server
    expose:
      - "8080"
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
    environment:
      - DB_ADDR=db